Info << "velocity min = " << gMin(mag(U)()) << " max = " << gMax(mag(U)()) << endl;
Info << "p_rgh min = " << gMin(p_rgh) << " max = " << gMax(p_rgh) << endl;
Info << "alpha1 min = " << gMin(alpha1) << " max = " << gMax(alpha1) << endl;
Info << "rhoPhi min = " << gMin(rhoPhi) << " max = " << gMax(rhoPhi) << endl;
Info << "phi min = " << gMin(phi) << " max = " << gMax(phi) << endl;
Info << "temperature min = " << gMin(T) << " max = " << gMax(T) << endl;
Info << "mu min = " << gMin(mu) << " max = " << gMax(mu) << endl;
Info << "rho min = " << gMin(rho) << " max = " << gMax(rho) << endl;
Info << "c min = " << gMin(phiFiber) << " max = " << gMax(phiFiber) << endl;

/*
Info << "p min = " << gMin(p) << " max = " << gMax(p) << endl;
Info << "alpha2 min = " << gMin(alpha2) << " max = " << gMax(alpha2) << endl;
Info << "rho1 min = " << gMin(rho1) << " max = " << gMax(rho1) << endl;
Info << "rho2 min = " << gMin(rho2) << " max = " << gMax(rho2) << endl;
*/

