#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# rm 0/alpha1.gz 0/alpha1 2>/dev/null
rm -rf *Flux
rm -rf ./processor[0-9]*/[1-9]*
rm -rf ./processor[0-9]*/0.[0-9]*

# cleanCase
cleanTimeDirectories

rm -rf dynamicCode

